#Source: https://data.ufl.edu/media/dataufledu/non-image-files/ODBC-Sample-Queries.sql
#To use the SQL here with the tables they have access to,the WH in the tablenamewill need to be replaced 
#with UF.  They will also need to prefix each tablenamewith the UFDL_PWCBA_DATA schema
#there will be no public synonyms to reference.
 
---ODBC Sample Queries
---Last Updated 6/18
---https://data.ufl.edu/data-management/student-data/
/*
 * Majors awarded for a term
 * Disclaimer: These are for degrees that are stored in PeopleSoft. i.e. some degrees from 1915 are not recorded in PeopleSoft, but are stored in a summary object. The degree summary object will be brought over in conversion.
 *
 */
SELECT
  M.ACAD_YEAR_SID,
  M.TERM_CD,
  D.UFID,
  E.ACAD_GROUP_LD,
  E.ACAD_PLAN_LD,
  J.ACAD_SPLAN_LD,
  L.DEGREE_CD,
  L.DEGREE_LD
FROM CS.WH_F_CPPS A,
  CS.WH_D_ACAD_ORG B,
  CS.WH_D_MDM_PERSON D,
  CS.WH_D_ACAD_PLAN E,
  CS.WH_D_ACAD_GROUP F,
  CS.WH_D_TERM H,
  CS.WH_D_ACAD_PROG I,
  CS.WH_D_ACAD_SPLAN J,
  CS.WH_D_DEGREE L,
  CS.WH_D_DEGREE_CO_STATUS O,
  CS.WH_D_TERM M
WHERE A.PERSON_SID = D.PERSON_SID
  AND A.ACAD_PLAN_SID = E.ACAD_PLAN_SID
  AND A.ACAD_GROUP_SID = F.ACAD_GROUP_SID
  AND A.EFF_TERM_SID = H.TERM_SID
  AND A.ACAD_PROG_SID = I.ACAD_PROG_SID
  AND A.ACAD_SPLAN_SID = J.ACAD_SPLAN_SID
  AND A.DEGREE_SID = L.DEGREE_SID
  AND A.ACAD_ORG_SID = B.ACAD_ORG_SID
  AND A.DEGREE_CO_STATUS_SID = O.DEGREE_CO_STATUS_SID
  AND O.DEGREE_CO_STATUS_CD = 'AW'
  AND E.ACAD_PLAN_TYPE_CD = 'MAJ'
  AND A.PROG_COMPL_TERM_SID = M.TERM_SID
  AND M.TERM_CD = :1
ORDER BY ACAD_YEAR_SID, TERM_CD, UFID, ACAD_PLAN_TYPE_LD;
/*
 * Minors awarded for a term
 * Disclaimer: These are for degrees that are stored in PeopleSoft. i.e. some degrees from 1915 are not recorded in PeopleSoft, but are stored in a summary object. The degree summary object will be brought over in conversion.
 */
SELECT
  M.ACAD_YEAR_SID,
  M.TERM_CD,
  D.UFID,
  B.ACAD_ORG_CD,
  B.ACAD_ORG_LD,
  E.ACAD_PLAN_LD
FROM CS.WH_F_CPPS A,
  CS.WH_D_ACAD_ORG B,
  CS.WH_D_MDM_PERSON D,
  CS.WH_D_ACAD_PLAN E,
  CS.WH_D_ACAD_GROUP F,
  CS.WH_D_TERM H,
  CS.WH_D_ACAD_PROG I,
  CS.WH_D_ACAD_SPLAN J,
  CS.WH_D_DEGREE L,
  CS.WH_D_DEGREE_CO_STATUS O,
  CS.WH_D_TERM M
WHERE A.PERSON_SID = D.PERSON_SID
  AND A.ACAD_PLAN_SID = E.ACAD_PLAN_SID
  AND A.ACAD_GROUP_SID = F.ACAD_GROUP_SID
  AND A.EFF_TERM_SID = H.TERM_SID
  AND A.ACAD_PROG_SID = I.ACAD_PROG_SID
  AND A.ACAD_SPLAN_SID = J.ACAD_SPLAN_SID
  AND A.DEGREE_SID = L.DEGREE_SID
  AND A.ACAD_ORG_SID = B.ACAD_ORG_SID
  AND A.DEGREE_CO_STATUS_SID = O.DEGREE_CO_STATUS_SID
  AND O.DEGREE_CO_STATUS_CD = 'AW'
  AND E.ACAD_PLAN_TYPE_CD = 'MIN'
  AND A.PROG_COMPL_TERM_SID = M.TERM_SID
  AND M.TERM_CD = :1
ORDER BY ACAD_YEAR_SID, TERM_CD, UFID, ACAD_PLAN_TYPE_LD;
/*
 * Certificates awarded for a term
 * Disclaimer: These are for degrees that are stored in PeopleSoft. i.e. some degrees from 1915 are not recorded in PeopleSoft, but are stored in a summary object. The degree summary object will be brought over in conversion.
 */
SELECT
  M.ACAD_YEAR_SID,
  M.TERM_CD,
  D.UFID,
  E.ACAD_GROUP_LD,
  E.ACAD_PLAN_LD,
  J.ACAD_SPLAN_LD,
  L.DEGREE_CD,
  L.DEGREE_LD
FROM CS.WH_F_CPPS A,
  CS.WH_D_ACAD_ORG B,
  CS.WH_D_MDM_PERSON D,
  CS.WH_D_ACAD_PLAN E,
  CS.WH_D_ACAD_GROUP F,
  CS.WH_D_TERM H,
  CS.WH_D_ACAD_PROG I,
  CS.WH_D_ACAD_SPLAN J,
  CS.WH_D_DEGREE L,
  CS.WH_D_DEGREE_CO_STATUS O,
  CS.WH_D_TERM M
WHERE A.PERSON_SID = D.PERSON_SID
  AND A.ACAD_PLAN_SID = E.ACAD_PLAN_SID
  AND A.ACAD_GROUP_SID = F.ACAD_GROUP_SID
  AND A.EFF_TERM_SID = H.TERM_SID
  AND A.ACAD_PROG_SID = I.ACAD_PROG_SID
  AND A.ACAD_SPLAN_SID = J.ACAD_SPLAN_SID
  AND A.DEGREE_SID = L.DEGREE_SID
  AND A.ACAD_ORG_SID = B.ACAD_ORG_SID
  AND A.DEGREE_CO_STATUS_SID = O.DEGREE_CO_STATUS_SID
  AND O.DEGREE_CO_STATUS_CD = 'AW'
  AND E.ACAD_PLAN_TYPE_CD = 'CRT'
  AND A.PROG_COMPL_TERM_SID = M.TERM_SID
  AND M.TERM_CD = :1
ORDER BY ACAD_YEAR_SID, TERM_CD, UFID, ACAD_PLAN_TYPE_LD;
/*
 * Breakdown of a degree and program status history
 * Filtered based on the degree code
 * Provides the entire history information for a degree, provides the Academic Program and Plan attached to the degree, and indicates if the degree was awarded.
 *
 */
SELECT
  C.PROG_STATUS_LD,
  A.UFID,
  TO_DATE (A.EFF_DT_SID, 'YYYYMMDD') AS EFFECTIVE_DATE,
  H.TERM_CD,
  I.ACAD_PROG_LD,
  E.ACAD_PLAN_LD,
  O.DEGREE_CO_STATUS_LD,
  L.DEGREE_CD,
  L.DEGREE_LD
FROM CS.WH_F_CPPS A,
  CS.WH_D_PROG_STATUS C,
  CS.WH_D_MDM_PERSON D,
  CS.WH_D_ACAD_PLAN E,
  CS.WH_D_ACAD_GROUP F,
  CS.WH_D_ACAD_CAR G,
  CS.WH_D_TERM H,
  CS.WH_D_ACAD_PROG I,
  CS.WH_D_ACAD_SPLAN J,
  CS.WH_D_ACAD_ORG K,
  CS.WH_D_DEGREE L,
  CS.WH_D_PROG_ACTION M,
  CS.WH_D_PROG_REASON N,
  CS.WH_D_DEGREE_CO_STATUS O
WHERE A.PROG_STATUS_SID = C.PROG_STATUS_SID
  AND A.PERSON_SID = D.PERSON_SID
  AND A.ACAD_PLAN_SID = E.ACAD_PLAN_SID
  AND A.ACAD_GROUP_SID = F.ACAD_GROUP_SID
  AND A.ACAD_CAR_SID = G.ACAD_CAR_SID
  AND A.EFF_TERM_SID = H.TERM_SID
  AND A.ACAD_PROG_SID = I.ACAD_PROG_SID
  AND A.ACAD_SPLAN_SID = J.ACAD_SPLAN_SID
  AND A.ACAD_ORG_SID = K.ACAD_ORG_SID
  AND A.DEGREE_SID = L.DEGREE_SID
  AND A.PROG_ACTION_SID = M.PROG_ACTION_SID
  AND A.PROG_REASON_SID = N.PROG_REASON_SID
  AND A.DEGREE_CO_STATUS_SID = O.DEGREE_CO_STATUS_SID
  AND L.DEGREE_CD = :1
ORDER BY UFID, EFF_DT_SID;
/*
 * Breakdown for active academic program student majors for an Academic group (/College/School) by term where they have enrolled in classes (F.ENRL_FLG = 'Y')
 * Filtered based on the academic group (the college that owns the student's academic program) and term
 * Provides the College/School (Academic Group), the major code (Academic plan), the specialization track (Academic Sub-plan), and the UF Class level for that term
 *
 */
SELECT
  A.UFID,
  B.TERM_CD AS EFFECTIVE_TERM,
  C.TERM_CD AS END_TERM,
  F.TERM_CD AS TERM_CD,
  F.STU_CLASSIFICATION_LEVEL,
  D.ACAD_PLAN_CD,
  D.ACAD_PLAN_LD,
  I.ACAD_SPLAN_CD,
  I.ACAD_SPLAN_LD,
  A.EFF_DT_SID,
  A.END_EFF_DT_SID,
  A.ACAD_PROG_CD,
  A.STU_DEGREE_NUM,
  A.ACAD_PLAN_SEQ_NUM,
  H.ACAD_CAR_SD ACAD_CAR,
  B.TERM_LD START_TERM,
  B.TERM_BEG_DT,
  C.TERM_LD END_TERM,
  C.TERM_END_DT,
  J.ACAD_GROUP_CD,
  F.TERM_CD
FROM CS.WH_F_CPPS A
JOIN CS.WH_D_TERM B ON (A.EFF_TERM_SID = B.TERM_SID)
JOIN CS.WH_D_TERM C ON (A.END_EFF_TERM_SID = C.TERM_SID)
JOIN CS.WH_D_ACAD_PLAN D ON (A.ACAD_PLAN_SID = D.ACAD_PLAN_SID)
JOIN CS.WH_D_PROG_STATUS E ON (A.PROG_STATUS_SID = E.PROG_STATUS_SID)
JOIN CS.WH_B_STU_TERM F ON (A.PERSON_SID = F.PERSON_SID AND F.TERM_CD BETWEEN B.TERM_CD AND C.TERM_CD)
JOIN CS.WH_D_ACAD_PROG G ON (A.ACAD_PROG_SID = G.ACAD_PROG_SID)
JOIN CS.WH_D_ACAD_CAR H ON (A.ACAD_CAR_SID = H.ACAD_CAR_SID)
JOIN CS.WH_D_ACAD_SPLAN I ON (A.ACAD_SPLAN_SID = I.ACAD_SPLAN_SID)
JOIN CS.WH_D_ACAD_GROUP J ON (A.ACAD_GROUP_SID = J.ACAD_GROUP_SID)
WHERE E.PROG_STATUS_CD = 'AC'
  AND F.ENRLMNT_FLAG = 'Y'
  AND D.ACAD_PLAN_TYPE_CD = 'MAJ'
  AND A.MAX_ROW_EFF_TERM_FLAG = 'Y'
  AND J.ACAD_GROUP_CD = :1
  AND F.TERM_CD = :2;
/*
 * Breakdown for active academic program majors for an Academic group(College or School) by an active term
 * Filtered based on the academic group (of the academic program) and term
 * Provides the College/School (Academic Group), the major/minor/certificate code (Academic plan), the specialization track (Academic Sub-plan)
 *
 */
SELECT
  A.UFID,
  B.TERM_CD AS EFFECTIVE_TERM,
  C.TERM_CD AS END_TERM,
  :2 AS TERM_CD,
  D.ACAD_PLAN_TYPE_LD,
  D.ACAD_PLAN_CD,
  D.ACAD_PLAN_LD,
  I.ACAD_SPLAN_CD,
  I.ACAD_SPLAN_LD,
  A.EFF_DT_SID,
  A.END_EFF_DT_SID,
  A.ACAD_PROG_CD,
  A.STU_DEGREE_NUM,
  A.ACAD_PLAN_SEQ_NUM,
  H.ACAD_CAR_SD ACAD_CAR,
  B.TERM_LD START_TERM,
  B.TERM_BEG_DT,
  C.TERM_LD END_TERM,
  C.TERM_END_DT
FROM CS.WH_F_CPPS A
JOIN CS.WH_D_TERM B ON (A.EFF_TERM_SID = B.TERM_SID)
JOIN CS.WH_D_TERM C ON (A.END_EFF_TERM_SID = C.TERM_SID)
JOIN CS.WH_D_ACAD_PLAN D ON (A.ACAD_PLAN_SID = D.ACAD_PLAN_SID)
JOIN CS.WH_D_PROG_STATUS E ON (A.PROG_STATUS_SID = E.PROG_STATUS_SID)
JOIN CS.WH_D_ACAD_PROG G ON (A.ACAD_PROG_SID = G.ACAD_PROG_SID)
JOIN CS.WH_D_ACAD_CAR H ON (A.ACAD_CAR_SID = H.ACAD_CAR_SID)
JOIN CS.WH_D_ACAD_SPLAN I ON (A.ACAD_SPLAN_SID = I.ACAD_SPLAN_SID)
JOIN CS.WH_D_ACAD_GROUP J ON (A.ACAD_GROUP_SID = J.ACAD_GROUP_SID)
WHERE E.PROG_STATUS_CD = 'AC'
  AND A.MAX_ROW_EFF_TERM_FLAG = 'Y'
  AND J.ACAD_GROUP_CD = :1
  AND :2 BETWEEN B.TERM_CD AND C.TERM_CD
ORDER BY UFID, ACAD_PLAN_TYPE_LD;
/*
 * Complete Academic Program Breakdown for a UFID
 * Filtered by UFID
 *
 */
SELECT
  A.UFID,
  B.TERM_CD AS EFFECTIVE_TERM,
  C.TERM_CD AS END_TERM,
  E.PROG_STATUS_LD,
  L.PROG_ACTION_LD,
  M.PROG_REASON_LD,
  H.ACAD_CAR_LD,
  J.ACAD_GROUP_LD,
  D.ACAD_PLAN_TYPE_LD,
  D.ACAD_PLAN_CD,
  D.ACAD_PLAN_LD,
  I.ACAD_SPLAN_CD,
  I.ACAD_SPLAN_LD,
  A.EFF_DT_SID,
  A.END_EFF_DT_SID,
  A.ACAD_PROG_CD,
  A.ACAD_PLAN_SEQ_NUM
FROM CS.WH_F_CPPS A,
  CS.WH_D_TERM B,
  CS.WH_D_TERM C,
  CS.WH_D_ACAD_PLAN D,
  CS.WH_D_PROG_STATUS E,
  CS.WH_D_ACAD_PROG G,
  CS.WH_D_ACAD_CAR H,
  CS.WH_D_ACAD_SPLAN I,
  CS.WH_D_ACAD_GROUP J,
  CS.WH_D_MDM_PERSON K,
  CS.WH_D_PROG_ACTION L,
  CS.WH_D_PROG_REASON M
WHERE A.EFF_TERM_SID = B.TERM_SID
  AND A.END_EFF_TERM_SID = C.TERM_SID
  AND A.ACAD_PLAN_SID = D.ACAD_PLAN_SID
  AND A.PROG_STATUS_SID = E.PROG_STATUS_SID
  AND A.ACAD_PROG_SID = G.ACAD_PROG_SID
  AND A.ACAD_CAR_SID = H.ACAD_CAR_SID
  AND A.ACAD_SPLAN_SID = I.ACAD_SPLAN_SID
  AND A.ACAD_GROUP_SID = J.ACAD_GROUP_SID
  AND A.PERSON_SID = K.PERSON_SID
  AND A.PROG_ACTION_SID = L.PROG_ACTION_SID
  AND A.PROG_REASON_SID = M.PROG_REASON_SID
  AND K.UFID = :1
ORDER BY B.TERM_CD;
/*
 * List Students within a Student Group as of today (Cohort (UFO), Special Program, etc)
 * Filtered by Student Group Code
 * Displays the UFIDS that are current in the student group
 *
 */
SELECT
  D.UFID
FROM CS.WH_B_PERSON_STU_GROUP A,
  CS.WH_D_STU_GROUP B,
SYSADM.WH_D_UF_DAY C,
  CS.WH_D_MDM_PERSON D
WHERE A.STU_GROUP_SID = B.STU_GROUP_SID
  AND B.STU_GROUP_CD = :1
  AND A.PERSON_SID = D.PERSON_SID
  AND C.DAY_SID BETWEEN A.EFF_DT_SID AND END_EFF_DT_SID
  AND C.UF_DAY_CUR_FLG = 'Y';
/*
 * Complete Term Breakdown for a UFID
 * Filtered by UFID
 * Displays the Primary activated academic career program plan information
 *
 */
SELECT
  B.UFID,
  E.TERM_CD,
  D.ACAD_LOAD_LD,
  A.CUR_GPA,
  A.CUM_GPA,
  C.ACAD_GROUP_LD AS PRIMARY_ACAD_GROUP,
  F.ACAD_PLAN_LD AS PRIMARY_ACAD_PLAN,
  H.DEGREE_LD AS PRIMARY_DEGREE,
  G.STU_CLASSIFICATION_LEVEL,
  A.TOT_GRADE_POINTS AS GRADE_POINTS,
  A.TOT_HOURS_TAKEN_GPA AS HOURS_CARRIED,
  A.TERM_HOURS_TRANSFERRED AS TRANSER_HOURS,
  A.TERM_HOURS_TAKEN_PROGRESS AS HOURS_TAKEN,
  A.TERM_HOURS_PASSED_PROGRESS AS HOURS_EARNED
FROM CS.WH_F_STU_TERM_PROGRESS A,
  CS.WH_D_MDM_PERSON B,
  CS.WH_D_ACAD_GROUP C,
  CS.WH_D_ACAD_LOAD D,
  CS.WH_D_TERM E,
  CS.WH_D_ACAD_PLAN F,
  CS.WH_D_ACAD_LEVEL G,
  CS.WH_D_DEGREE H
WHERE A.PERSON_SID = B.PERSON_SID
  AND A.ACAD_GROUP_SID = C.ACAD_GROUP_SID
  AND A.ACAD_LOAD_SID = D.ACAD_LOAD_SID
  AND A.TERM_SID = E.TERM_SID
  AND A.ACAD_PLAN_SID = F.ACAD_PLAN_SID
  AND A.ACAD_LEVEL_SID_BOT = G.ACAD_LEVEL_SID
  AND A.DEGREE_SID = H.DEGREE_SID
  AND B.UFID = :1
ORDER BY TERM_CD;
/*
 * Complete Course Breakdown for a UFID
 * Filtered by UFID
 * Displays the Primary activated academic career information, course information, technology indicator, section component, grade, and GPA information
 *
 */
SELECT
  B.UFID,
  E.TERM_CD,
  C.ACAD_CAR_LD AS PRIMARY_STDNT_ACAD_CAREER,
  F.ACAD_ORG_CD AS CLASS_DEPT,
  F.UF_COURSE_NUMBER,
  F.CLASS_NUM AS SECTION,
  F.COURSE_LD,
  F.COMPONENT_TYPE_LD,
  H.INSTRUCTION_MODE_LD,
  A.GRADE_POINTS,
  A.HOURS_TAKEN,
  G.GRADE_CD
FROM CS.WH_F_STU_ENRLMT A,
  CS.WH_D_MDM_PERSON B,
  CS.WH_D_ACAD_CAR C,
  CS.WH_D_TERM E,
  CS.WH_D_CLASS F,
  CS.WH_D_GRADE G,
  CS.WH_D_INSTRUCTION_MODE H
WHERE A.PERSON_SID = B.PERSON_SID
  AND A.ACAD_CAR_SID = C.ACAD_CAR_SID
  AND A.TERM_SID = E.TERM_SID
  AND A.GRADE_SID = G.GRADE_SID
  AND A.CLASS_SID = F.CLASS_SID
  AND A.INSTRUCTION_MODE_SID = H.INSTRUCTION_MODE_SID
  AND B.UFID = :1
ORDER BY TERM_CD, UF_COURSE_NUMBER;
/*
 * Enrollment Breakdown for a term
 * Filtered by TERM
 * Displays the Primary activated academic career program plan information, course information, technology indicator, section component, grade, and GPA information
 *
 */
SELECT
  B.UFID,
  E.TERM_CD,
  C.ACAD_CAR_LD AS PRIMARY_STDNT_ACAD_CAREER,
  F.ACAD_ORG_CD AS CLASS_DEPT,
  F.UF_COURSE_NUMBER,
  F.CLASS_NUM AS SECTION,
  F.COURSE_LD,
  F.COMPONENT_TYPE_LD,
  H.INSTRUCTION_MODE_LD,
  A.GRADE_POINTS ,
  A.HOURS_TAKEN,
  G.GRADE_CD,
  A.LAST_ENRLMT_DTTM
FROM CS.WH_F_STU_ENRLMT A,
  CS.WH_D_MDM_PERSON B,
  CS.WH_D_ACAD_CAR C,
  CS.WH_D_TERM E,
  CS.WH_D_CLASS F,
  CS.WH_D_GRADE G,
  CS.WH_D_INSTRUCTION_MODE H
WHERE A.PERSON_SID = B.PERSON_SID
  AND A.ACAD_CAR_SID = C.ACAD_CAR_SID
  AND A.TERM_SID = E.TERM_SID
  AND A.GRADE_SID = G.GRADE_SID
  AND A.CLASS_SID = F.CLASS_SID
  AND A.INSTRUCTION_MODE_SID = H.INSTRUCTION_MODE_SID
  AND E.TERM_CD = :1
ORDER BY TERM_CD, UF_COURSE_NUMBER;
/*
 * Course Section Enrollment Summary
 * Filtered by TERM
 * Displays course number, section department, course description, technology indicator, enrollment status, section type, enrollment capacity, reserved capacity, total enrollment
 *
 */
SELECT
  F.UF_COURSE_NUMBER,
  F.ACAD_ORG_CD,
  F.COURSE_LD,
  F.INSTRUCTION_MODE_LD,
  F.ENRLMT_STATUS_LD,
  F.COMPONENT_TYPE_LD,
  F.ENRLMT_CAP,
  F.RESERVE_CAP,
  F.TOT_ENRLMT
FROM CS.WH_D_CLASS F
WHERE TERM_CD = :1;
